name = "vortex_interactive/argon"
version = "2.0.26+toolchainlib.2"
description = "Argon - Full featured tool for Roblox development"
authors = [
	"AridAjd <aridthedev@gmail.com>",
	"DervexDev <contact@dervex.dev> (https://dervex.dev/)",
]
repository = "https://github.com/Vortex-Interactive/pesde-tooling/tree/main/bins/argon"
includes = ["init.luau", "README.md", "pesde.toml"]

[engines]
lune = "^0.10.3"
pesde = "^0.7.1"

[target]
environment = "lune"
bin = "init.luau"

[dependencies]
result = { name = "lukadev_0/result", version = "^1.2.1", index = "official" }
option = { name = "lukadev_0/option", version = "^1.2.1", index = "official" }
toolchainlib = { workspace = "vortex_interactive/toolchainlib" }

[indices]
default = "https://github.com/Vortex-Interactive/pesde-index"
official = "https://github.com/pesde-pkg/index"
