name = "pesde/argon"
version = "2.0.21"
description = "Argon - Full featured tool for Roblox development"
authors = [
	"AridAjd <aridthedev@gmail.com>",
	"DervexDev <contact@dervex.dev> (https://dervex.dev/)",
]
repository = "https://github.com/pesde-pkg/tooling/tree/main/bins/argon"
includes = ["init.luau", "README.md", "pesde.toml"]

[target]
environment = "lune"
bin = "init.luau"

[dependencies]
result = { name = "lukadev_0/result", version = "^1.2.0" }
option = { name = "lukadev_0/option", version = "^1.2.0" }
core = { workspace = "pesde/toolchainlib", version = "^" }

[indices]
default = "https://github.com/pesde-pkg/index"
