name = "pesde/selene"
version = "0.28.0"
description = "A blazing-fast modern Lua linter written in Rust"
authors = ["CompeyDev <hi@devcomp.xyz>", "Kampfkarren <kampfkarren@gmail.com>"]
repository = "https://github.com/pesde-pkg/tooling/tree/main/bins/selene"
includes = ["init.luau", "README.md", "pesde.toml"]

[engines]
lune = ">=0.8.7"
pesde = "^0.6.0-rc.6"

[target]
environment = "lune"
bin = "init.luau"

[dependencies]
result = { name = "lukadev_0/result", version = "^1.2.0" }
option = { name = "lukadev_0/option", version = "^1.2.0" }
core = { workspace = "pesde/toolchainlib", version = "^" }

[indices]
default = "https://github.com/pesde-pkg/index"
