name = "pesde/selene"
version = "0.29.0+toolchainlib.1"
description = "A blazing-fast modern Lua linter written in Rust"
authors = ["CompeyDev <hi@devcomp.xyz>", "Kampfkarren <kampfkarren@gmail.com>"]
repository = "https://github.com/pesde-pkg/tooling/tree/main/bins/selene"
includes = ["init.luau", "README.md", "pesde.toml"]

[engines]
lune = "^0.10.2"
pesde = "^0.7.0"

[target]
environment = "lune"
bin = "init.luau"

[dependencies]
result = { name = "lukadev_0/result", version = "^1.2.1" }
option = { name = "lukadev_0/option", version = "^1.2.1" }
toolchainlib = { workspace = "pesde/toolchainlib" }

[indices]
default = "https://github.com/pesde-pkg/index"
