name = "pesde/zap"
version = "0.6.22"
description = "A lightning fast networking solution for roblox."
authors = ["CompeyDev <hi@devcomp.xyz>", "Redblox Organization"]
repository = "https://github.com/pesde-pkg/tooling/tree/main/bins/zap"
includes = ["init.luau", "README.md", "pesde.toml"]

[engines]
lune = "^0.8.7"
pesde = "^0.6.0"

[target]
environment = "lune"
bin = "init.luau"

[dependencies]
result = { name = "lukadev_0/result", version = "^1.2.0" }
option = { name = "lukadev_0/option", version = "^1.2.0" }
core = { workspace = "pesde/toolchainlib", version = "^" }

[indices]
default = "https://github.com/pesde-pkg/index"
