name = "pesde/blink"
version = "0.15.6"
description = "An IDL compiler written in Luau for ROBLOX buffer networking"
authors = ["CompeyDev <hi@devcomp.xyz>", "Axen <axen@frombloxware.com>"]
repository = "https://github.com/pesde-pkg/tooling/tree/main/bins/blink"
includes = ["init.luau", "README.md", "pesde.toml"]

[engines]
lune = ">=0.8.7"
pesde = "^0.6.0-rc.6"

[target]
environment = "lune"
bin = "init.luau"

[dependencies]
result = { name = "lukadev_0/result", version = "^1.2.0" }
option = { name = "lukadev_0/option", version = "^1.2.0" }
core = { workspace = "pesde/toolchainlib", version = "^" }

[indices]
default = "https://github.com/pesde-pkg/index"
