name = "pesde/toolchainlib"
description = "A Luau library for implementing toolchain management"
version = "0.1.13"
license = "MIT"
repository = "https://github.com/pesde-pkg/tooling/tree/main/toolchainlib"
includes = ["src/**/*.luau", "pesde.toml", "LICENSE", "README.md"]

[engines]
lune = "^0.8.7"
pesde = "^0.6.0"

[target]
environment = "lune"
lib = "src/init.luau"

[dependencies]
pathfs = { name = "jiwonz/pathfs", version = "^0.3.0" }
dirs = { name = "jiwonz/dirs", version = "^0.3.0" }
unzip = { name = "0x5eal/unzip", version = "^0.1.0", target = "luau" }

[peer_dependencies]
result = { name = "lukadev_0/result", version = "^1.2.0" }
option = { name = "lukadev_0/option", version = "^1.2.0" }

[indices]
default = "https://github.com/pesde-pkg/index"
