name = "pesde/toolchainlib"
description = "A Luau library for implementing toolchain management"
version = "0.1.2"
license = "MIT"
repository = "https://github.com/pesde-pkg/tooling/tree/main/toolchainlib"
includes = ["src", "pesde.toml", "LICENSE", "README.md"]

[target]
environment = "lune"
lib = "src/init.luau"

[dependencies]
pathfs = { name = "jiwonz/pathfs", version = "^0.1.0" }
dirs = { name = "jiwonz/dirs", version = "^0.1.1" }

[peer_dependencies]
result = { name = "lukadev_0/result", version = "^1.2.0" }
option = { name = "lukadev_0/option", version = "^1.2.0" }

[indices]
default = "https://github.com/daimond113/pesde-index"
