name = "vortex_interactive/toolchainlib"
description = "A Luau library for implementing toolchain management"
version = "0.2.1"
license = "MIT"
repository = "https://github.com/Vortex-Interactive/pesde-tooling/tree/main/toolchainlib"
includes = ["src/**/*.luau", "pesde.toml", "LICENSE", "README.md"]

[engines]
lune = "^0.10.4"
pesde = "^0.7.1"

[target]
environment = "lune"
lib = "src/init.luau"

[dependencies]
pathfs = { name = "jiwonz/pathfs", version = "^0.6.0", index = "official" }
dirs = { name = "jiwonz/dirs", version = "^0.6.0", index = "official" }
unzip = { name = "0x5eal/unzip", version = "^0.2.0", target = "luau", index = "official" }

[peer_dependencies]
result = { name = "lukadev_0/result", version = "^1.2.1", index = "official" }
option = { name = "lukadev_0/option", version = "^1.2.1", index = "official" }

[indices]
default = "https://github.com/Vortex-Interactive/pesde-index"
official = "https://github.com/pesde-pkg/index"
