name = "pesde/rojo"
version = "7.4.4"
description = "Rojo enables Roblox developers to use professional-grade software engineering tools"
authors = ["CompeyDev <hi@devcomp.xyz>", "Lucien Greathouse <me@lpghatguy.com>"]
repository = "https://github.com/pesde-pkg/tooling/tree/main/bins/rojo"
includes = ["init.luau", "README.md", "pesde.toml"]

[target]
environment = "lune"
bin = "init.luau"

[dependencies]
result = { name = "lukadev_0/result", version = "^1.2.0" }
option = { name = "lukadev_0/option", version = "^1.2.0" }
core = { workspace = "pesde/toolchainlib", version = "^" }

[indices]
default = "https://github.com/pesde-pkg/index"
