name = "pesde/asphalt"
version = "1.1.0"
description = "An assets-as-files tool for Roblox"
authors = ["CompeyDev <hi@devcomp.xyz>", "Jack T <jack@jackt.space>"]
repository = "https://github.com/pesde-pkg/tooling/tree/main/bins/asphalt"
includes = ["init.luau", "README.md", "pesde.toml"]

[engines]
lune = "^0.10.2"
pesde = "^0.7.0"

[target]
environment = "lune"
bin = "init.luau"

[dependencies]
result = { name = "lukadev_0/result", version = "^1.2.1" }
option = { name = "lukadev_0/option", version = "^1.2.1" }
toolchainlib = { workspace = "pesde/toolchainlib" }

[indices]
default = "https://github.com/pesde-pkg/index"
